services:
  api:
    build: .
    container_name: finance_dashboard_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-jwt}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/app/uploads
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
    networks:
      - finance-network

  db:
    image: postgres:16.4
    container_name: finance_dashboard_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - finance-network

networks:
  finance-network:
    name: finance-network
    driver: bridge

volumes:
  postgres_data: