services:
  api:
    build: .
    container_name: finance_dashboard_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/finance_dashboard
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-jwt}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/app/uploads
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
    networks:
      - finance-network

  db:
    image: postgres:13
    container_name: finance_dashboard_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=finance_dashboard
    ports:
      - "5432:5432"
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  postgres_data: